#!/bin/bash

echo "Certbot Renew Certificates ..."
echo
echo "Host(s): $LETSENCRYPT_HOST"
echo "E-mail:  $LETSENCRYPT_MAIL"
echo

certbot run --apache -d $LETSENCRYPT_HOST --non-interactive --email $LETSENCRYPT_MAIL --agree-tos --no-eff-email --keep-until-expiring --dry-run


echo "Done."
